### ISSUE TITLE
Future Scope: Timeline

### ISSUE THREAD

**Issue by AnnickS** [AnnickS/Items-is-Items#10]
This is a quick description of where we expect our project to go over the course of 3 quarters.

**Comment by pplluumm** [comment]
The focus of this game is the mystery of item uses. The completed project will have a start screen that has access to single player and multiplayer. The player will then enter the game world where they control a character and can store and use items with an RuneScape-esque inventory.
	By the end of fall quarter we intend to finish the minimum viable product. This includes a character, an inventory, and items that you can put into the inventory and use. Winter Quarter we will implement LAN Multiplayer, where two different computers are able to interact in the same game world. Then in Spring quarter, we will cleanup the interface, add menus, add more items, and if we have time make the game support multiple platforms.
