### ISSUE TITLE
Quests

### ISSUE THREAD

**Issue by AnnickS** [AnnickS/Items-is-Items#102]
Quests:
- Text/Description from NPC
- Condition (What NPC wants)
- Reward (Indicated by surroundings)

Dialogue:
- Trigger to show Text
- Dialogue Box
- Moving through Text
- Closing Box

State Machine:
- Start State (dialogue/item needed)
- Transition State (dialogue/reward)
- End State (dialogue/->New quest state?)

**Comment by pplluumm** [comment]
Showing Dialog
