### ISSUE TITLE
Create MVP Prototype Parts

### ISSUE THREAD

**Issue by pplluumm** [AnnickS/Items-is-Items#45]
get together or talk on discord and create a list of things you liked / disliked about each MVP
Figure out a couple of things that the true MVP for the quarter will have

**Comment by AnnickS** [comment]
Prototype differences:

Follow Movement:
Follow player movement
Follow behind player

Grab And Use Item:
Click to pickup/Click to drop
Click and hold to pickup/Let go to drop
Flick to move

Inventory:
Inventory Interacts with World
Inventory 'ghosts' through World

Item Use:
1. Player collides with item -> Inventory / Drag item and drop to use
2. Player collides with item -> Uses / Drag item and drop to inventory
3. NPC collides with item -> Inventory / Drag item and drop to use
4. NPC collides with item -> Uses / Drag item and drop to inventory

Player Movement:
WASD
Click-and-Go (Moves player where screen is clicked towards clicked area)
Hold-and-Go (Moves player only when click is held down toward mouse)

**Comment by AnnickS** [comment]
Follow Movement:
Follow behind Player

Grab and Use Item:
Click and hold to pickup/Let go to drop

Inventory:
Inventory 'ghosts' through World

Item Use:
1 and 4

Player Movement:
WASD
