### ISSUE TITLE
Sprint 3: Test Quests/Content

### ISSUE THREAD

**Issue by AnnickS** [AnnickS/Items-is-Items#84]
#Quests
One Main Storyline Quest- Heal the Dog
One Rats on the Road Quest- Break town gate with cheesy door
#Map
A World Map
#Item
Cheese
Medicine for Dog
Plant to give to Doctor
#NPC
Doctor for Medicine
Dog that is sick
Rat Plague >:D

**Comment by pplluumm** [comment]
Annick
 - NPC Dog (bc she owns a dog)
-  Item Medicine (bc dog need medicine)
Job
- NPC Doctor
- Item Herb
Jordan
- NPC Rat
- Item Cheese
